name: sandbox

environments:
  production:
    manifest: ./test/sandbox/manifests/production.yml
  staging:
    manifest: ./test/sandbox/manifests/staging.yml

services:
  ping:
    manifest: ./test/sandbox/services/ping/manifest.yml
  hello:
    manifest: ./test/sandbox/services/hello/manifest.yml

ci:
  defaults:
    build:
      env:
        # COMPOSE_FILE: $(pwd)/test/sandbox/docker-compose.yml
        TAG: $BUILD_VERSION-$BUILD_ID
        # TAG: latest
      command: |
        docker-compose build $BUILD_SERVICE
      #  docker-compose push $BUILD_SERVICE