version: '3.8'

services:

  ping:
    image: "jbrunton/g3ops-sandbox-ping:${TAG?}"
    build:
      context: ./test/sandbox/services/ping
  
  hello:
    image: "jbrunton/g3ops-sandbox-hello:${TAG?}"
    ports:
      - 3000:3000
    build:
      context: ./test/sandbox/services/hello
