name: sandbox

environments:
  production:
    manifest: ./test/sandbox/manifests/production.yml
  staging:
    manifest: ./test/sandbox/manifests/staging.yml

services:
  ping:
    manifest: ./test/sandbox/services/ping/manifest.yml
  hello:
    manifest: ./test/sandbox/services/hello/manifest.yml

ci:
  defaults:
    build:
      env:
        TAG: $BUILD_VERSION-$BUILD_ID
      command: |
        echo "$G3OPS_DOCKER_ACCESS_TOKEN" | docker login -u "$G3OPS_DOCKER_USERNAME" --password-stdin
        docker-compose build $BUILD_SERVICE
        docker-compose push $BUILD_SERVICE
  workflows:
    build:
      values: ./test/sandbox/workflow.yml
      target: ./.github/workflows/ci-sandbox-build-test.yml
