package lib

import (
	"fmt"

	"github.com/spf13/afero"
)

func newTestContext() (*afero.Afero, *G3opsContext) {
	fs := CreateMemFs()
	context := &G3opsContext{
		Dir: ".g3ops",
	}
	return fs, context
}

const invalidTemplate = `
local workflow = {
  on: {
    push: {
      branches: [ "develop" ],
    },
  }
};
std.manifestYamlDoc(workflow)
`

const invalidWorkflow = `# File generated by g3ops, do not modify
# Source: .g3ops/workflows/test.jsonnet
"on":
  "push":
    "branches":
    - "develop"
`

const exampleTemplate = `
local workflow = {
  on: {
    push: {
      branches: [ "develop" ],
    },
  },
	jobs: {
		test: {
			"runs-on": "ubuntu-latest",
			steps: [
			  { run: "echo Hello, World!" }
      ]
    }
  }
};
std.manifestYamlDoc(workflow)
`

const exampleWorkflow = `# File generated by g3ops, do not modify
# Source: .g3ops/workflows/test.jsonnet
"jobs":
  "test":
    "runs-on": "ubuntu-latest"
    "steps":
    - "run": "echo Hello, World!"
"on":
  "push":
    "branches":
    - "develop"
`

func newTestWorkflowDefinition(name string, content string) *workflowDefinition {
	return &workflowDefinition{
		name:        name,
		source:      fmt.Sprintf(".g3ops/workflows/%s.jsonnet", name),
		destination: fmt.Sprintf(".github/workflows/%s.yml", name),
		content:     content,
	}
}
