name: ci-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: build
        run: go build

      - name: configure environment
        env:
          REF: ${{ github.ref }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "::set-env name=GIT_BRANCH::${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "::set-env name=REF::$REF"
          echo "::set-env name=EVENT_NAME::$EVENT_NAME"

      - name: check env
        run: env

      - name: test
        run: go test ./...
