name: ci-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: build
        run: go build

      - name: configure environment for pull request
        if: github.event_name == 'pull_request'
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "::set-env name=GIT_BRANCH::$GITHUB_HEAD_REF"
          echo "::set-env name=GIT_COMMIT_SHA::$HEAD_SHA"

      - name: configure environment for push
        if: github.event_name == 'push'
        run: |
          echo "::set-env name=GIT_BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-env name=GIT_COMMIT_SHA::$GITHUB_SHA"

      - name: prepare test reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: test
        run: go test -coverprofile c.out ./...

      - name: upload coverage
        run: ./cc-test-reporter after-build
