name: ci-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: build
        run: go build

      - name: configure environment
        run: echo "::set-env name=GITHUB_BRANCH::${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

      - name: check env
        run: env

      - name: test
        run: go test ./...
