name: ci-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
env:
  GOPATH: ${{ github.workspace }}
  GO111MODULE: off

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: build
        run: go build
      - name: test
        run: go test ./...
