name: ci-release

on:
  deployment

jobs:

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment.task == 'release' }}
    steps:
    - run: npm install
    - run: npm run release -- ${INCREMENT:-minor}
      env:
        INCREMENT: ${{ github.event.deployment.increment }}
