name: ci-sandbox-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  manifest_check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      buildMatrix: ${{ steps.check.outputs.buildMatrix }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: install g3ops
        run: go get github.com/jbrunton/g3ops

      - name: check manifest
        id: check
        run: g3ops set-outputs build-matrix

  build:
    runs-on: ubuntu-latest
    needs: manifest_check
    if: ${{ needs.manifest_check.outputs.buildRequired == true }}
    strategy:
      matrix: ${{ fromJson(needs.manifest_check.outputs.buildMatrix) }}
    env:
      G3OPS_DOCKER_ACCESS_TOKEN: ${{ secrets.G3OPS_DOCKER_ACCESS_TOKEN }}
      G3OPS_DOCKER_USERNAME: ${{ secrets.G3OPS_DOCKER_USERNAME }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'

      - name: install g3ops
        run: go get github.com/jbrunton/g3ops

      - name: build
        run: g3ops service build ${{ matrix.service }}
