name: test-workflow-dispatch

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'Test input' 

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
